title: Haruhiko Yoshioka's Homepage
markdown: kramdown
url: "https://hy20191108.github.io"
baseurl: ""

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - CLAUDE.md
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - _scripts

sass:
  sass_dir: _sass
  style: :compressed

# Google Analytics measurement ID.
ga_analytics: G-9HMZ89BY4J
