# Setup
title: Haruhiko Yoshioka's Homepage
show_downloads: true
markdown: kramdown

# Site settings for SEO
url: "https://hy20191108.github.io"
baseurl: ""

# Gems
plugins:
  - jekyll-coffeescript
  # - jekyll-default-layout
  - jekyll-gist
  # - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-9HMZ89BY4J

# Specify the author for blog posts
author:
  name: Mark Otto
  url: https://twitter.com/mdo
  email: markdotto@gmail.com

# Custom vars
version: 3.0.0
